Feature/#121 s3 image
Kernel360/f1-Orury-Backend pull request #124
Opened 2024-01-11 09:33 UTC by oxix97

## 개요

S3 Config에서 access key, secret key를 사용하여 S3에 접근합니다.

S3 Service에서 지정한 Bucket에 접근하며, MultipartFile을 파일로 변환하여 저장합니다. 이때 SnowFlake에서 파일의 이미지를 저장합니다.

![image](https://github.com/Kernel360/f1-Orury-Backend/assets/72330632/d7d26362-2960-44da-9839-be74171595cc)

해당 알고리즘이 이해가 되지않아 현재시간 + 유저의 아이디값으로 임시로 적용하였으며 추후에 멘토링을 하며 개선할 예정입니다.

ImageController에서 테스트할 수 있으며 postman으로 API 호출시 S3 orury-image라는 버킷에 저장된 결과를 확인가능하며 response인 url를 통해서도 확인이 가능합니다.

closed #121 

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-01-12 05:06 UTC, kkkapuq requested changes
수고하셨습니다~

요청드린부분만 적용해주시면 좋을 것 같습니다!

2024-01-12 05:06 UTC, kkkapuq commented on orury-client/src/main/java/org/fastcampus/oruryclient/ImageController.java
> +            @RequestParam("userId") Long userId,
유저 id를 별도로 받을 필요가 있나요?

2024-01-12 05:06 UTC, kkkapuq commented on orury-client/src/main/java/org/fastcampus/oruryclient/ImageController.java
> +    @PostMapping("/image")
@Operation 및 @Description 추가 부탁드립니다!

2024-01-12 05:06 UTC, kkkapuq commented on orury-client/src/main/resources/application.yaml
> +      secretKey: ${AWS_S3_SECRET_KEY}
요것들은 Jasypt로 감싸주시고 키는 슬랙으로 공유 부탁드립니다!

2024-01-12 05:10 UTC, oxix97 commented on orury-client/src/main/java/org/fastcampus/oruryclient/ImageController.java
> +    @PostMapping("/image")
넵

2024-01-12 05:12 UTC, oxix97 commented on orury-client/src/main/java/org/fastcampus/oruryclient/ImageController.java
> +            @RequestParam("userId") Long userId,
타임스탬프 + 고유아이디 + 유저아이디로 만들고 있어 현재는 필요하며 멘토링이후 정책상 어떻게 적용하는지 여쭤보면 수정할 것 같습니다.

2024-01-12 05:30 UTC, yejincode commented on orury-common/src/main/java/org/fastcampus/orurycommon/s3/S3Service.java
> +        removeFile(file);
이 임시파일을 삭제한다는 것은, 이미 업로드에 성공했기 때문에 임시파일을 가지고 있을 필요가 없어서 그런걸로 이해하면 되나요?

2024-01-12 05:36 UTC, yejincode commented on orury-common/src/main/java/org/fastcampus/orurycommon/s3/Snowflake.java
이 코드는 Twitter의 Snowflake ID 생성 알고리즘을 구현한 것입니다. Snowflake 알고리즘은 분산 시스템에서 고유한 ID를 생성하는 데 사용됩니다. 이 ID는 시간 순서대로 생성되며, 동일 시간에 여러 ID가 생성되어도 고유함을 유지합니다.

이 코드의 주요 부분들을 다음과 같이 설명할 수 있습니다:

1. **변수 선언:** 알고리즘에 사용되는 비트 수를 정의합니다. 41비트는 타임스탬프에 사용되며, 10비트는 노드 ID(분산 시스템 내에서 유일한 머신 ID)에 사용되고, 12비트는 시퀀스 번호에 사용됩니다.

2. **생성자:** Snowflake 객체를 생성할 때 노드 ID와 사용자 정의 에포크(기준 시간)를 입력으로 받습니다. 노드 ID는 지정하지 않을 경우, 네트워크 인터페이스의 MAC 주소를 기반으로 생성합니다.

3. **nextId 메서드:** 새로운 Snowflake ID를 생성합니다. 현재 타임스탬프가 마지막으로 생성한 ID의 타임스탬프와 같으면 시퀀스 번호를 증가시키고, 그렇지 않으면 시퀀스를 0으로 재설정합니다. 타임스탬프, 노드 ID, 시퀀스 번호를 합쳐 최종 ID를 생성합니다.

4. **timestamp 메서드:** 현재 시간을 밀리초 단위로 반환하며, 사용자 정의 에포크를 뺀 값을 반환합니다.

5. **waitNextMillis 메서드:** 다음 밀리초까지 대기합니다. 이는 같은 밀리초에 시퀀스 번호가 소진된 경우에 사용됩니다.

6. **parse 메서드:** 주어진 Snowflake ID를 사용하여 원래의 타임스탬프, 노드 ID, 시퀀스 번호를 추출합니다.

이러한 방법으로, Snowflake 알고리즘은 분산 시스템에서 고유하고 시간 순서대로 정렬된 ID를 생성할 수 있습니다.


-> gpt4 답변으론 이렇게 흘러가는 알고리즘 이군요,,,! 어쨌든 snowflake의 알고리즘을 사용해서 유일한 파일명을 만든다.. ~ 로 이해하겠습니다

2024-01-12 05:38 UTC, yejincode approved these changes

2024-01-12 05:40 UTC, oxix97 commented on orury-common/src/main/java/org/fastcampus/orurycommon/s3/S3Service.java
> +        removeFile(file);
넵 맞습니다. 이미 만들었기 때문에 삭제합니다.

2024-01-12 05:41 UTC, oxix97 commented on orury-common/src/main/java/org/fastcampus/orurycommon/s3/Snowflake.java
해당 오픈소스의 내용을 그대로 가져다가 사용하는데 아직 잘 활용하지 못했고 어떻게 만들지도 못정했기때문에 멘토링이후에 비슷하게 가져간다라고 생각해주시면 좋을 것 같습니다.

2024-01-15 01:44 UTC, kkkapuq approved these changes
변경사항 확인했습니다. 수고하셨습니다

2024-01-15 02:32 UTC, merged