Refactor : gym의 total_score, review_count 필드 추가에 따른 review 리팩토링
Kernel360/f1-Orury-Backend pull request #189
Opened 2024-01-25 06:50 UTC by yejincode

## 개요

gym의 total_score, review_count 필드가 추가 됨에 따라 review 리팩토링을 진행했습니다.
review가 생성/ 수정/ 삭제 됨에 따라서, gym의 total_score, review_count에 값이 반영되도록 했습니다. 
그리고 그에 따라 review_service testcode도 리팩토링 했습니다 . 

* 리뷰 생성 : total_score = total_score + 작성한 리뷰의 score; / review_count = review_count++;
* 리뷰 수정 : total_score = total_score - 기존 작성한 리뷰의 score + 작성한 리뷰의 score;
* 리뷰 삭제 : total_score = total_score - 작성한 리뷰의 score; / review_count = review_count--;

커밋 순서대로 보면 될 것 같습니다 !

closed #173 

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-01-25 07:26 UTC, GBGreenBravo requested changes
리팩토링 고수..!

2024-01-25 07:26 UTC, GBGreenBravo commented on orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymDetailResponse.java
> +        Float totalScore,
프론트에 전달할 때는 총점수 말고, 평균점수로 보내야 할듯 합니다!
여기랑 GymsResponse에 reviewScore로만 슬쩍 바꿔주시면 감사하겠습니다~!

2024-01-25 07:26 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/repository/GymRepository.java
> +    void subtractTotalScore(@Param("gymId") Long gymId, @Param("reviewScore") float reviewScore);
sum이 합계라는 뜻이어서,
' add / subtract '로 가거나, 기존대로 ' increase / decrease '로 메서드명 정하는 게 좋은 것 같습니다..!

2024-01-25 07:27 UTC, kkkapuq approved these changes
특이사항은 없는것같습니다 수고하셨어요

2024-01-25 07:38 UTC, yejincode commented on orury-client/src/main/java/org/fastcampus/oruryclient/gym/converter/response/GymDetailResponse.java
> +        Float totalScore,
그렇겠네요 계산하는 로직 추가해서 gym 조회 시에 반영하겠습니다 !

2024-01-25 07:39 UTC, yejincode commented on orury-domain/src/main/java/org/fastcampus/orurydomain/gym/db/repository/GymRepository.java
> +    void subtractTotalScore(@Param("gymId") Long gymId, @Param("reviewScore") float reviewScore);
오호.. 영잘알,,, 반영하겠습니다|
add/ substract로 할게요 !

2024-01-25 08:14 UTC, oxix97 requested changes
수고하셨습니다~~

2024-01-25 08:14 UTC, oxix97 commented on orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
```java
        reviewService.updateReview(updateReviewDto, image); //before
        reviewService.updateReview(beforeReviewDto, updateReviewDto, image); //after
```
변동하신 이유가 궁금합니다. !!

2024-01-25 08:14 UTC, oxix97 commented on orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
> +        imageUploadAndSave(updateReviewDto, images);
ReviewController와 동일한 내용입니다.

2024-01-25 08:14 UTC, oxix97 commented on orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewControllerTest.java
> +
혹시 자동 정렬 하시면 import static이 위로 가시나요?

2024-01-25 08:25 UTC, yejincode commented on orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
update 시에 리뷰에 score가 바뀔 수 있기 때문에, 
1. beforeReviewDto의 score를 가져와서 gym의 total_score에 빼는 작업
2. updateReviewDto의 score를 가져와서 gym의 total_score에 더하는 작업
을 수행하기 위해 beforeReviewDto를 추가했습니다 !

2024-01-25 08:26 UTC, yejincode commented on orury-client/src/main/java/org/fastcampus/oruryclient/review/service/ReviewService.java
> +        imageUploadAndSave(updateReviewDto, images);
위에 댓글 달았습니다 ~

2024-01-25 08:26 UTC, yejincode commented on orury-client/src/test/java/org/fastcampus/oruryclient/review/controller/ReviewControllerTest.java
> +
넵 따로 건든 부분은 없습니다

2024-01-25 09:51 UTC, oxix97 commented on orury-client/src/main/java/org/fastcampus/oruryclient/review/controller/ReviewController.java
아 넵 이해했습니다~~!!

2024-01-25 09:51 UTC, oxix97 approved these changes

2024-01-26 02:36 UTC, GBGreenBravo approved these changes
수고하셨습니당~~

2024-01-26 02:36 UTC, merged