Feat : 마이페이지 내가 쓴 리뷰, 게시글, 댓글 조회 기능 구현 및 WithCursorResponse 리팩토링
Kernel360/f1-Orury-Backend pull request #202
Opened 2024-01-29 05:44 UTC by yejincode

## 개요

* 리뷰, 게시글, 댓글 기능이 완성됨에 따라 마이페이지에서도 내가 쓴 내용을 조회할 수 있도록 기능을 추가했습니다.

* 추가적으로 PostWithCursorResponse, ReviewWithCursorResponse, CommentWithCursorResponse 등 cursor를 담는 똑같은 역할을 수행하지만, 각자 다른 Response를 입력받기 때문에 모든 response에 대해 ~~WithCursorResponse를 만들어야 했습니다. (객체 지향(?) 적인 설계를 하고 싶어..) T로 모든 response를 받아서 cursor 값을 담을 수 있는 WithCursorResponse를 만들었습니다 . 만약 cursor값 외에도 다른 필드를 추가해야한다면 해당 WithCursorResponse를 상속받아서 필드 추가하면 됩니다. 현재에는 UserController에만 적용했고, 리뷰 받은 후에 다른 도메인에도 적용하려고 합니다 ! 

* 각 기능이 추가됨에 따라 작성한 메소드에 따라 테스트 코드도 추가했습니다. (Post, Review, Comment Service Test)

closed #194 

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-01-29 07:14 UTC, GBGreenBravo commented on orury-client/src/main/java/org/fastcampus/oruryclient/global/IdIdentifiable.java
> +    Long id();
이 필드는 어디서 활용되는지 설명 부탁드립니다..!

2024-01-29 07:21 UTC, oxix97 requested changes
수고하셨습니다~~

2024-01-29 07:21 UTC, oxix97 commented on orury-client/src/main/java/org/fastcampus/oruryclient/global/IdIdentifiable.java
> +    Long id();
이 필드는 어디서 활용되는지 설명 부탁드립니다..!22

2024-01-29 07:21 UTC, oxix97 commented on orury-client/src/main/java/org/fastcampus/oruryclient/global/WithCursorResponse.java
> +    }
IdIdentifiable이 어떤 역할로 사용되는지 궁금합니다!!

2024-01-29 07:38 UTC, yejincode commented on orury-client/src/main/java/org/fastcampus/oruryclient/global/IdIdentifiable.java
> +    Long id();
![image](https://github.com/Kernel360/f1-Orury-Backend/assets/69861207/75dd3e9f-5539-4ee2-b066-54adb276386d)

WithCursorResponse가 모든 객체를 받아 cursor를 담아줄 수 있도록 하기 위해서 처음에는 
`
public record WithCursorResponse<T> ()
`
와 같이 작성하려고 했습니다. 근데 그런 경우에는 아래의 of() 메소드에서 문제가 발생합니다.
이유는, of() 메소드에서 id() 메소드를 사용하고 있는데 WithCursorResponse가 받은 객체가 id()메소드를 포함하지 않을 수 있기 때문입니다. 
따라서, WithCursorResponse가 받는 객체 T는 반드시 id 메소드를 가져야한다고 명시해주어야 합니다.

명시를 위해 IdIdentifiable 인터페이스를 통해 이 인터페이스를 구현하는 객체는 id()메소드를 가질 수 있도록 작성했습니다. 
이 후 response converter (ex. 마이페이지의 내 게시글, 리뷰, 댓글 조회를 위한 MyreviewResponse, MyPostResponse, MyComment response)는 IdIdentifiable를 구현하도록 했습니다. 

이렇게 하면 IdIdentifiable 인터페이스를 구현한 객체만 WithCursorResponse를 사용할 수 있게 됩니다 !

2024-01-29 07:38 UTC, yejincode commented on orury-client/src/main/java/org/fastcampus/oruryclient/global/WithCursorResponse.java
> +    }
위에 답글 달았습니다 !!

2024-01-29 07:53 UTC, GBGreenBravo commented on orury-client/src/main/java/org/fastcampus/oruryclient/global/IdIdentifiable.java
> +    Long id();
WithCursorResponse가 인자에서 id()만을 활용하는 클래스이므로 그런 이슈가 있었군요! 
매우 합리적인 해결책이라고 생각합니다~~

2024-01-29 07:53 UTC, GBGreenBravo approved these changes

2024-01-29 10:03 UTC, oxix97 commented on orury-client/src/main/java/org/fastcampus/oruryclient/global/IdIdentifiable.java
> +    Long id();
id값이 Null 인 경우의 예외를 줄이기 위해서 작성하신 걸로 이해해도 괜찮을까여?

2024-01-29 10:04 UTC, oxix97 approved these changes

2024-01-29 10:15 UTC, yejincode commented on orury-client/src/main/java/org/fastcampus/oruryclient/global/IdIdentifiable.java
> +    Long id();
Id값이 Null 이라기 보다는 Id 메소드가 없는 경우를 배제하고자 작성했다고 이해하는 것이 좋을 것 같습니다 !

2024-01-30 05:41 UTC, kkkapuq approved these changes
IdIdentifiable 활용한거.. 잘 이해는 안가는데 나중에 댓글 컨트롤러 쓰면서 한번 점검해보겠습니다

2024-01-30 05:41 UTC, kkkapuq commented on orury-client/src/main/java/org/fastcampus/oruryclient/global/IdIdentifiable.java
> +    Long id();
와 인터페이스 활용 진짜 잘하신거같아요 잘 보고갑니다

2024-01-30 05:49 UTC, merged