Feat : 좌표영역 내 암장목록 조회 api
Kernel360/f1-Orury-Backend pull request #326
Opened 2024-03-02 03:35 UTC by GBGreenBravo

## 개요
- GymEntity에서 기존에 totalScore이 Floaf로 돼있었는데, null값을 허용할 이유가 없다고 생각해서 float로 변경했습니다.
- GymEntity에서 DB에는 String으로 저장돼 있는 값을 double로 가져올 수 있도록, columnDefinition을 활용했습니다.
- 좌표영역 내 암장목록 조회 api
  - GymAreaRequest에서 현재 경도, 현재 위도, 좌표영역(AreaGrid)를 받도록 구현했습니다.
  - 좌표영역을 전달할 때 상하좌우 각각 전달할 수도 있겠지만, 불필요하게 코드가 길어질 것 같아
  Map<Stirng, Double>로 꺼내 쓰도록 구현했습니다.
  - AreaGrid 객체를 생성하지 않고, Map<String, Double> areaGrid로 활용할 수 있겠지만,
  개인적인 의견으로는 AreaGrid로 관리/구현하는 게 더 가독성이 좋은 듯하여 이렇게 구현했습니다.

closed #325

## PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-04 02:29 UTC, kkkapuq approved these changes
특이사항 없습니다! 수고하셨어요
늘 솔선수범해주셔서 감사합니다

2024-03-04 02:29 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/gym/interfaces/request/AreaGrid.java
> +//        return gridMap;
추후에 수정 여지가 있는 코드는 // TODO 로 작성하는 것이 찾기 쉬울 것 같습니다!

2024-03-04 02:29 UTC, kkkapuq commented on orury-domain/src/main/java/org/orury/domain/gym/domain/dto/GymDto.java
> +        float totalScore,
primitive type으로 변경하신 이유가 궁금합니다

2024-03-04 05:20 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/gym/interfaces/request/AreaGrid.java
> +//        return gridMap;
넵! 그런 컨벤션을 적용해본 적이 없어서 몰랐네요..! 유용한 조언 감사합니다~!

2024-03-04 05:23 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/gym/domain/dto/GymDto.java
> +        float totalScore,
다른 필드들(좋아요 수)와 마찬가지로, 참조타입이 아닌 원시타입으로 선언한 이유는
참조타입으로 선언하면 null을 허용하게 되는 것인데, totalScore에서 null을 허용할 필요가 없다고 생각했기 때문입니다!

2024-03-04 05:46 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/gym/interfaces/GymController.java
> +    @Operation(summary = "좌표 내 암장 목록 검색", description = "현지 위치 좌표와 영역 좌표(경도, 위도)를 받아, 영역 내의 암장 목록을 가까운 순으로 돌려준다.")
현지 위치 -> 현재 위치 오타 수정하면 좋을 것 같습니다 !
(현지님은 지금 창가 쪽에 잘 앉아 계심,,)

2024-03-04 06:08 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/gym/interfaces/GymController.java
> +    @Operation(summary = "좌표 내 암장 목록 검색", description = "현지 위치 좌표와 영역 좌표(경도, 위도)를 받아, 영역 내의 암장 목록을 가까운 순으로 돌려준다.")
수정했습니다 ㅋㅋㅋ

2024-03-04 06:30 UTC, oxix97 requested changes
수고하셨습니다₩~

2024-03-04 06:30 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/gym/domain/dto/GymDto.java
> +        float totalScore,
Gym의 totalScore 기본값이 0 이라서 좋은것같습니다

2024-03-04 06:30 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/gym/infrastructure/GymReaderImpl.java
>      }
해당 로직이 어떻게 동작하는지 설명해주시면 좋을거같습니다.

2024-03-04 06:57 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/gym/infrastructure/GymReaderImpl.java
>      }
findBy 위도Between(bottom위도, top위도) And 경도Between(left경도, rigth경도) OrderBy좋아요수;
이렇게 쿼리를 날려, 위경도 좌표영역 내의 암장들을 좋아요순으로 가져오게 됩니다!

SELECT * FROM gym 
WHERE latitude BETWEEN ? AND ? 
AND longitude BETWEEN ? AND ? 
ORDER BY like_count;

2024-03-05 05:08 UTC, yejincode approved these changes

2024-03-05 05:10 UTC, oxix97 approved these changes
수고하셨습니다~~

2024-03-05 05:10 UTC, merged