Refactor : Auth 리팩토링 with DDD&DIP
Kernel360/f1-Orury-Backend pull request #328
Opened 2024-03-04 02:05 UTC by GBGreenBravo

## 개요
기존에 변경해왔던 방식과 동일하게 리팩토링 진행했습니다.
다만, 조금 특이한 점이 있다면, 활용되는 Service가 많습니다. (AuthService, OAuthService, JwtTokenService)
이 Service들에서 서로 필요한 부분에서 아래와 같은 계층을 가진다고 생각하시면 이해에 도움이 될 듯 합니다.
![image](https://github.com/Kernel360/f1-Orury-Backend/assets/147565215/becd0267-8567-436b-ba09-c90644699d4e)

closed #327 

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-04 06:07 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/auth/application/AuthFacade.java
> +        return authService.reissueJwtTokens(request);
해당 코드 내에서 
`JwtTokenService.reissueJwtTokens(request);`
대신 AuthService 내에 새로운 메서드를 만들어서 처리하신 이유가 있을까요? 
보통 Facade에서 다른 도메인서비스를 받아서 처리하는데, Auth는 ServiceImpl에서 받고 있어 왜 그렇게 작성하셨는지 궁금합니다 !

2024-03-04 06:28 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
> +    private final OAuthServiceManager oAuthServiceManager;
JwtTokenService와 OAuthServiceManager의 경우, Reader/Store가 아닌 Service를 사용하는 이유가 무엇인가요? 
토큰 발급과 같이 복잡한 로직에 대한 메서드는 따로 빼서 구현하는 것이 역할별로 더 구분되기에 그렇게 했다! 고 이해해도 될까요 ?!

2024-03-04 06:45 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
> +    private final OAuthServiceManager oAuthServiceManager;
DB에 접근하는 로직은 RefreshToken과 User Reader/Store로 따로 다뤄줬습니다!
JwtTokenService와 OAuthServicemanager의 경우에는 DB에 접근하는 것이 주 기능이 아니기에 하위의 로직을 다루는 하위 계층의 Service로 생각해주시면 됩니다! 
AuthServiceImpl에서 바로 RefreshToken과 User Reader/Store 의존받아 구현할 수는 있겠지만, 그렇게 된다면 코드의 책임이 과도하게 많아질 것 같아 Service 계층을 분리시켰습니다!

그래서 예진님께서 마지막에 이해하신 바가 맞습니다!!

2024-03-04 06:55 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
> +    private final OAuthServiceManager oAuthServiceManager;
저번에 같은 계층 사이에서 참조하고 있을 경우, 순환 참조가 발생할 가능성이 있다고 하여서 무조건 피해야지 생각하고 있었는데 어쨌든 인터페이스 기반으로 의존성 주입해서 순환참조될 일은 없을 것 같네요! 분리한 것이 훨씬 깔끔한 것 같습니다

2024-03-04 07:01 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
> +    private final OAuthServiceManager oAuthServiceManager;
넵 그래서 AuthService // OAuthService&JwtTokenService 와 같이 계층을 나눈 것에 대해서 앞으로도 위배되지 않도록 구현되어야 합니다!

2024-03-04 07:24 UTC, oxix97 requested changes
수고하셨습니다~~

2024-03-04 07:35 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/auth/application/AuthFacade.java
그렇긴 합니다..! 아무래도 기존 컨벤션을 따른 것이라, Facade도 구현했습니다.!

2024-03-04 07:36 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
> +        }
DB의 User테이블의 email 필드가 UNIQUE가 걸려있어서, 기존에 존재하는 email의 User가 들어오면 DataIntegrityViolationException 예외를 반환시킵니다!

2024-03-04 07:38 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/auth/application/oauth/KakaoOAuthService.java
> +    }
이건 카카오 OAuth서버로 보낸 것에 대한 답변이라, 카카오 로그인된 이메일을 반환합니다!
그래서 이 값이 null인 경우에는, 카카오 로그인의 응답에 이메일이 정상적으로 실리지 않은 상황이고,
이메일 값이 특정 값으로 존재하고, 저희 DB를 조회했을 때 exist하지 않는 경우가 비회원의 경우입니다!

2024-03-04 07:56 UTC, kkkapuq approved these changes
수고하셨습니다

확실히 개발해본 내용은 이해가 잘되네요.. ^^;

2024-03-04 07:56 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
> +        String email = oAuthService.getEmailFromOAuthCode(request.code());
LoginStrategy -> OAuthService
Kakao/AppleStrategy -> Kakao/AppleService 로 이동하셨군요. 좋은 방법인 것 같습니다.
어떻게 해야할 지 조금 애매했었거든요.

2024-03-04 08:09 UTC, yejincode approved these changes

2024-03-05 03:36 UTC, oxix97 approved these changes
수고하셨습니다~~

2024-03-05 03:41 UTC, merged