Refactor : 유저 도메인 변경 및 Ban 유저 관련 수정사항 반영
Kernel360/f1-Orury-Backend pull request #343
Opened 2024-03-05 07:44 UTC by oxix97

## 개요

- 유저 테이블 컬럼 변경 :  is_deleted -> status
정상유저, 삭제된 유저만 감지하는 것이 아닌 활성화된 유저, 비활성화된 유저, 관리자로인한 제제를 받은 유저 등으로 관리하기 위함

- 로그인 조건 추가
JWT으로 유저를 관리하지만 실질적인 권한으로 나누기에는 수정할 파일이 많습니다.
간단히 유저가 가지고 있는 status값을 판단하여 토큰 발급 여부를 결정하는 조건을 추가하였습니다. 

- 유저 도메인 변경에 따른 여러 가지 변경 사항 ex) LoginDTO, DTO....

closed #339

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-05 07:53 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserStatus.java
> +    L("ROLE_LEAVE", "탈퇴한 유저");
해당 Enum이 코드 전반에 사용된다면, E/B/L의 의미를 코드에서 확인할 수 없어 가독성이 떨어질 것 같습니다.
ENABLE, BAN, LEAVE와 같이 명시적으로 활용하면 좋겠습니다.

2024-03-05 08:16 UTC, GBGreenBravo requested changes

2024-03-05 08:16 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
> +
이 로직을 reIssueJwtTokens()메서드에도 추가해줘야 합니다.
제제 당한 유저가, 로그인 상태를 유지한 채로 토큰재발급만 하며 서비스를 계속 이용할 수 있기 때문입니다.

다만 위를 반영한다 해도, 운영자가 제재를 가한 시점부터 제재된 유저의 액세스토큰 만료기한까지는(최대 7일), 
현재 코드로 제재할 수 없습니다.

그렇다고 제재 확인용 필터를 추가해서 캐시메모리를 활용한다 해도, 이게 맞나?하는 확신이 없긴 합니다.
그래서, 일단은 액세스토큰의 만료시간(현재 7일)을 12시간과 같이 더 줄일 필요가 있을 듯 합니다.

2024-03-05 08:16 UTC, GBGreenBravo commented on orury-admin/src/main/java/org/orury/admin/user/UserServiceImpl.java
>      public void deleteUser(UserDto userDto) {
User의 기존 필드를 isDeleted에서 status로 바꿨으므로, 굳이 delete를 사용하지 않아도 될 듯 합니다!
blockUser()이나 banUser()을 활용하는 건 어떨까요?

2024-03-05 08:16 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserDto.java
> +    }
제재당한 유저닉네임을 "제재된 유저입니다"와 같이 변환할 필요까지는 없을 것 같다는 의견입니다..!
그리고 탈퇴유저의 경우에는 해당 유저가 작성한 모든 것이 삭제되거나, DB에 저장되는 값을 바꿔버리기 때문에 다뤄줄 필요 없기도 합니다!

2024-03-05 08:34 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserStatus.java
> +    L("ROLE_LEAVE", "탈퇴한 유저");
반영 완료입니다~

2024-03-05 08:40 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserStatusConverter.java
> +                .orElseThrow(() -> new InfraImplException(UserErrorCode.INVALID_USER));
매우 적절한 InfraImplExeption 사용인 것 같습니다!

2024-03-05 08:42 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserDto.java
> +    }
이거 롤백하고 제제된 유저에 대한 게시글, 댓글, 리뷰 같은 경우는 유저가 탈퇴하지 않으면 사라지지 않는데 관련된 사항을 손보는게 좀 더 좋은 방법인거 같긴합니다.

2024-03-05 08:43 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserDto.java
> +    }
아니면 제제된 유저만 거를까여?

2024-03-05 08:44 UTC, oxix97 commented on orury-admin/src/main/java/org/orury/admin/user/UserServiceImpl.java
>      public void deleteUser(UserDto userDto) {
저도 동일한 의견입니다 바로 반영갑니다

2024-03-05 08:45 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserDto.java
> +    }
그것도 있네요..! 정책적인 결정사항이라, 여러 옵션이 있을 듯 합니다.
옵션 1: 어드민의 수동 삭제..ㅎㅎ
옵션 2: 제재된 유저의 모든 것 삭제
옵션 3: 어드민이 유저 제재할 때 특정 시점을 설정해서, 그 시점 이후로 생성/수정된 해당 유저의 모든 것 삭제.

2024-03-05 08:59 UTC, oxix97 commented on orury-client/src/main/java/org/orury/client/auth/application/AuthServiceImpl.java
> +
exist로 리프레시 토큰이 있는지 없는지 검증한다음 토큰 발급이 이뤄지면 유저 밴할때 토큰을 지워도 되나여?

2024-03-05 16:19 UTC, kkkapuq approved these changes
수고하셨습니다~~!

2024-03-05 16:19 UTC, kkkapuq commented on orury-domain/src/main/java/org/orury/domain/user/domain/dto/UserStatus.java
> +    LEAVE("ROLE_LEAVE", "탈퇴한 유저", "L");
오늘 말했던 이 맵퍼를 이런식으로 사용이 가능하군요.. 배우고 갑니다

2024-03-06 02:53 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/auth/application/jwt/JwtTokenServiceImpl.java
> +                    .orElseThrow(() -> new BusinessException(AuthErrorCode.BAN_USER));
이거 추가된 위치가 비회원인 경우라, 항상 BusinessException(AuthErrorCode.BAN_USER))을 반환할 것으로 예상합니다!
그렇다면 회원인 경우, 토큰에 id가 있으므로 findEnableUserById 활용하면 될 것으로 생각합니다!

2024-03-06 09:10 UTC, GBGreenBravo approved these changes
의논에 따라 계속 수정을 많이하셔서,, 진짜 수고 많으셨습니다!!!

2024-03-06 09:37 UTC, yejincode approved these changes
제가 먼저 Ban될 거 같아요

2024-03-06 10:28 UTC, merged