Update README.md
Kernel360/f1-Orury-Backend pull request #369
Opened 2024-03-08 09:44 UTC by yejincode

## 개요

간단하게 리드미 작성했습니다!

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-09 05:40 UTC, GBGreenBravo approved these changes

2024-03-11 01:19 UTC, kkkapuq requested changes

2024-03-11 01:19 UTC, kkkapuq commented on README.md
> +클라이밍 짐 정보와 리뷰를 한눈에!
클라이밍 짐 -> 암장
이 더 좋을 것 같습니다.

2024-03-11 01:22 UTC, GBGreenBravo approved these changes
뼈대 좋습니다~

2024-03-11 01:27 UTC, yejincode commented on README.md
> +클라이밍 짐 정보와 리뷰를 한눈에!
반영하겠습니다 !

2024-03-11 05:08 UTC, kkkapuq approved these changes
수고하셨습니다
플젝 마무리할 때 다시 한번 보시죵

2024-03-12 09:11 UTC, oxix97 approved these changes

2024-03-12 09:11 UTC, merged