feat: 운영 DB 정보 yml 파일 추가
Kernel360/f1-Orury-Backend pull request #372
Opened 2024-03-11 06:19 UTC by yejincode

## 개요

이전에 작업해둔 운영 DB 관련 application.yml 파일이 실종되어있어 다시 추가했습니다.
실행해보려면 설정의 프로파일에서 prod로 바꾸면 운영 DB로 연결됩니다. 

closed #371

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-11 06:19 UTC, GBGreenBravo approved these changes
되찾았다,, yml..!

2024-03-11 06:30 UTC, kkkapuq requested changes

2024-03-11 06:30 UTC, kkkapuq commented on orury-client/src/main/resources/application-prod.yml
> +server.port: 8087
이친구 포함되어야 하는건가요?
아니라면 지우고, 포함되어야 한다면 8085가 되어야 할 것 같습니다!

2024-03-11 06:32 UTC, yejincode commented on orury-client/src/main/resources/application-prod.yml
> +server.port: 8087
테스트용으로 설정해뒀는데, 해당 부분 삭제했습니다. !

2024-03-11 06:32 UTC, kkkapuq approved these changes
수고하셨어용!

2024-03-12 09:11 UTC, oxix97 approved these changes

2024-03-12 09:11 UTC, merged