Feat : 크루 생성 API 구현
Kernel360/f1-Orury-Backend pull request #378
Opened 2024-03-12 02:01 UTC by GBGreenBravo

## 개요
### @Valid를 활용한 Request Validation
- 비즈니스로직은 아니지만, 들어오는 값 검증이 필요한 경우 (예시: 태그는 최소1개 최대3개, 크루 최대인원은 100명까지만 가능)
  - 해당 검증에 대해 Service단에서 해주는 건 코드 낭비가 심할 것으로 생각하여,
  - Controller에서 받는 Request에 @Valid를 설정해주고, CrewCreateRequest에서
    - JakartaEE의 validation / Hibernate의 validator에서 기본적으로 제공하는 어노테이션을 통해 검증해줬고,
    - Enum의 경우는, EnumValidator에서 검증되는 @EnumValue라는 커스텀 어노테이션을 생성하여 해당 Enum의 값에 포함되는지 검증해줬습니다.
  - GlobalExceptionHander에서 해당 검증에서 발생하는 Exception(MethodArgumentNotValidException)을 반환하도록 설정했습니다. 
### Crew DB/엔티티 변경 
- 기획이 확정됨에 따라, CrewTag 테이블과 Entity를 추가해줬습니다.
  - CrewTag 엔티티의 Crew는 나중의 검색 말고는 활용되는 여지가 작을 것으로 생각하여 FetchType.LAZY로 설정했습니다.
- Crew에서는 min_age, max_age, gender, permission_required, question, answer_required가 추가됐고, regions의 문자열길이를 줄여줬습니다.
- Crew 엔티티에서
  - DB에 1과 0으로 true/false를 뜻하는 필드들은 NumericBooleanConverter(기본제공)를 활용해서 변환하고,
  - Enum에 해당하는 region과 gender는 커스텀한 Converter를 구현하여 변환합니다.
### Crew 생성 API 구현
- CrewServiceImpl에서 아래와 같은 로직으로 크루가 생성돼도록 구현했습니다.
  1. 유저가 참여하고 있는 크루 수 검증 (최대 3개)
  2. 이미지 저장
  3. 이미지 포함한 Crew 저장
  4. CrewTag 생성
  5. CrewMember 추가

closed #354

## PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-12 08:05 UTC, c0olcode commented
이미지 변경 API는 기존의 방식대로 3번도 좋고, 1번도 각각의 장단점이 존재해서 무엇이 좋을지 모르겠네요...
3번이라면 setter를 사용하지 않는 대신 객체를 하나 더 만들게 되어 그만큼의 메모리 소모가 있다는 것이 단점인 것 같고,
1번의 경우 setter는 객체 내부 상태를 직접 노출하기에, 외부 코드에서 의도치 않게 값을 변경하면 객체 일관성 유지가 어려울 수 있다. 는 것이 단점이라고 생각합니다.

현재 플젝 코드는 이미 역할별로 계층을 쪼개고 쪼개고 쪼개고.. 했기에  사용되는 계층이 한정되어 있고, 코드 흐름도 잘 보인다고 생각합니다. 1번의 단점이 제가 생각한 것만 있다면, setter를 사용하더라도 특정한 계층에서만 쓰이기에 일관성 유지와 같은 단점을 충분히 보완할 수 있을 것이라고 생각합니다. 

전 둘다.. 괜찮습니다.. .

2024-03-12 08:43 UTC, c0olcode commented on orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewCreateRequest.java
> +        @Min(value = 7, message = "최저 연령을 7세 이상으로 설정해 주세요.")
왜 7인지 궁금합니다

2024-03-12 08:43 UTC, c0olcode commented on orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewCreateRequest.java
> +        @Length(min = 3, max = 15, message = "크루명은 3~15 글자수로 설정 가능합니다.")
백엔드에서 한번 더 검증은 해주지만, API 요청 시에 검증할 수 있기에 검증되는 내용들 프론트에 공유해서 API 호출 없이 프론트에서 먼저 걸러질 수 있게 하면 좋을 것 같습니다!

2024-03-12 08:43 UTC, c0olcode commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewDto.java
> +        List<String> tags
Dto는 Entity의 필드를 그대로 가지며 data transfer의 역할을 한다고 알고 있습니다. Crew엔티티에는 tag가 포함되지 않는데, Dto에 tag를 추가한 이유가 있을까요?

2024-03-12 08:43 UTC, c0olcode commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGenderConverter.java
> +    }
여기에서 다른 익셉션이 아닌 InfraException을 던지는 이유가 무엇인가요?

2024-03-12 08:43 UTC, kkkapuq reviewed
수고하셨습니다.
이미지나 status 값을 변경하는 api의 건에 대해서는 3번이 제일 좋아보입니다.
1번은 엔티티엔 세터를 놓지 말자는 저희 프로젝트의 대원칙을 위배하는 것이고
2번은 엔티티에 메서드가 있는것이 엔티티가 과한 책임을 들고있는 것 같습니다.

따라서 3번이긴 한데, 이것도 탐탁치는 않은 것 가타용.
멘토링 통해서 좀 더 좋은 방법이 있는지 찾아보는게 좋을 것 같습니다.

2024-03-12 08:43 UTC, kkkapuq commented on orury-domain/src/main/java/org/orury/domain/crew/domain/entity/Crew.java
> +    private boolean isDeleted;
이친구는 애플리케이션에서 True / False로 받는 값을 int형으로 변환해주는 건가 보네요.
개인적으로는 굳이 바꿔야되나? 라는 생각이 들긴합니다.
다른 엔티티(comment)도 컨벤션에 맞게 수정을 해야 하기도 하구요.

User.status처럼 추후에 뭔가 Status로 관리를 한다고 하면 기존에 boolean을 상정해서 True / False 로만 로직을 작성해놨을텐데, 확장에 복잡도가 생기지 않을까 생각해봅니다.

2024-03-12 08:43 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
> +    }
둘다 Long 타입으로 != 로 해줘도 될 것 같은데 Objects.equals로 비교하시는 이유가 궁금합니다!
가독성 측면 때문일까요?

2024-03-12 08:43 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/crew/interfaces/response/CrewResponse.java
> +        Region region,
Enum으로 바꾼거 너무 좋은것같습니다!!

2024-03-12 08:43 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
>          Review review = reviewReader.findById(reviewId)
Read를 하는 쿼리에 대해선 트랜잭션을 안먹이는게 좋을 것 같습니다. 아니면 따로 트랜잭션을 먹이신 이유가 있으실까요?

2024-03-12 08:43 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
> +    @Transactional(readOnly = true)
22

2024-03-12 08:43 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
> +    @Transactional(readOnly = true)
33

2024-03-12 08:43 UTC, kkkapuq commented on orury-domain/src/main/java/org/orury/domain/global/domain/Region.java
> +public enum Region {
전국으로 확장시킨다고 가정해보면... 이걸 어떻게 해야될지 생각을 좀 해봐야겠네요

2024-03-12 08:44 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewCreateRequest.java
> +        @Min(value = 7, message = "최저 연령을 7세 이상으로 설정해 주세요.")
이런 값은 기획에서는 고려되지 않은, 임의로 설정한 값이라, 어떤 값으로든 바꿔도 상관없습니다..!

2024-03-12 08:45 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewCreateRequest.java
> +        @Length(min = 3, max = 15, message = "크루명은 3~15 글자수로 설정 가능합니다.")
매우 동의합니다!!
유저가 화면에서 미리 해당 제한 알고 있는게 더 좋을 듯합니다!

2024-03-12 08:48 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewDto.java
> +        List<String> tags
Entity 필드를 그대로 가지되, Data Transfer Object라는, 프로세스 간 객체 전달에 맞게, Crew 데이터에서 거의 항상 요구되는 CrewTag를 포함시키는 게 옳다고 생각했습니다! CrewTagDto를 따로 관리할 경우, 불필요한 코드가 많아지기도 하기에 이렇게 구현했습니다.
DB에 저장되고 해당 내용을 객체로 관리하는 Entity와 Dto의 구분이 여기서 유의미해지는 게 아닐까,,, 하는 도전적인 시도였습니다.
다른 팀원분들의 의견도 궁금합니다..!

2024-03-12 08:49 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGenderConverter.java
> +    }
Converter가 적용되는 시점은 DB데이터와 Entity데이터 간의 변화, 즉 DB에 저장된 값의 유효성 여부와 관련돼있다고 생각되어,
Service 단에서 쓰는 BusinessException말고, InfraException을 채택했습니다.

2024-03-12 08:50 UTC, c0olcode commented on orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
>          Review review = reviewReader.findById(reviewId)
민협님 대신 답변을 달자면, 운영 DB에서 readOnly가 붙은 것은 readreplica로 라우팅되도록 코드가 나와있어서 트랜잭션을 먹이긴 해야합니다

2024-03-12 08:54 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/crew/domain/entity/Crew.java
> +    private boolean isDeleted;
코드 단계에서 isDeleted = NumberConstants.IS_NOT_DELETED 와 같이 길게 구현되는 것보다,
isDeleted = false와 같은 코드가 가독성이 더 좋다고 생각해서 boolean으로 변경했습니다.
만약에 다른 엔티티에도 컨벤션을 맞춰야 한다면, 책임지고 바꾸겠습니다..!ㅎㅎ

뒤에 주신 의견은 0/1로 관리하나 boolean으로 관리하나, 확장의 복잡도에는 차이가 없을 것으로 생각하는데,
혹시 어떤 부분에서 더 복잡하다고 생각하셨을까요...?

2024-03-12 09:00 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/global/domain/Region.java
> +public enum Region {
생각하기로는 기존의 지역구분보다, 암장에 적절한 Depth를 나눠서 생각해봐야 할 듯합니다.
광역시에는 암장이 비교적 많을테니, 
1depth: 서울, 부산, 인천, 광주, 강원, 충북, 전북, 경북과 같이 설정하고,
2depth: 서울 중구, 부산 동래구, ... , 강원 강릉시, 충북 괴산군
과 같은 depth를 가져가고, 암장이 거의 없는 2depth의 경우 또 묶어줘야하지 않을까,,, 생각했습니다.

다만, 서울 한정이라 Region을 구로만 구분해놨습니다.

2024-03-12 09:26 UTC, yejincode commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGenderConverter.java
> +    }
DDD 아키텍처로 리팩토링해서 계층 간의 역할이 확실해졌기 때문에 익셉션도 계층 별로 다르게 하면 좋을 것 같다는 생각으로 InfraException을 만들었습니다. Infra 계층에서는 외부 DB와 통신을 하기에, 외부 통신 시 발생하는 오류를 잡기 위한 목적이었고, FileException도 비슷한 목적으로 쓰이고 있습니다. 외부 통신이 아닌 유효성 여부에 따라 InfraException을 던지기에는 익셉션 이름이 모호하다.,,? 는 생각이 문득 듭니다! 

이대로 민협님의 코드를 가려면, Infra 계층에서 발생하는 모든 예외를 처리하기 위한 Exception으로 맞추는 것이 좋을 것 같습니다!
(+ S3말고 다른 외부 서버와 통신한다면, 해당 서버에 관련된 Exception을 새로 만들어서 통신 오류 등을 잡으면 될 것 같아요)

2024-03-12 09:31 UTC, yejincode commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewDto.java
> +        List<String> tags
- 기존 방식대로 하면 Facade까지 CrewDto, CrewTagDto를 가져와서 response에 담는다.
- 민협님 방식대로 하면 ServiceImpl에서 tag 정보까지 CrewDto에 담아 Facade에 넘긴다.

의 차이일 듯한데, 기존 방식이면 크루를 조회하는 모든 도메인의 Facade 코드가 길어질 듯 하네요
민협님이 말씀하신 문제 때문에 Aggregate 개념이 있는 게 아닐까? 라는 생각이 문득 듭니다 (아님 말고...)

멘토링 받아보면 좋을 것 같아요 !

2024-03-12 13:57 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
> +    }
NullPointerException 때문에 관습적으로 쓴 거라, != 가 더 가독성이 좋다고 생각되는 거면 수정하겠습니다! 말씀해주세요~!

2024-03-12 14:10 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
>          Review review = reviewReader.findById(reviewId)
트랜잭션(readOnly=true)가 일반적으로 좋다는 것만 알고, 관습적으로 붙여왔기에 더 찾아보아도,, 저희 코드에서 더 나은 동작을 하는 건지에 대해서는 확신이 없습니다.. 더 공부가 필요한 부분이고,
예진님 말씀대로 db replication 때문이면 명시적으로 달아줄 필요가 있긴 하겠네요..!

2024-03-12 14:11 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewDto.java
> +        List<String> tags
맞습니다!! Aggregate 개념이 정확할 듯 합니다!

2024-03-13 03:29 UTC, oxix97 requested changes
수고하셨습니다~~~

2024-03-13 03:29 UTC, oxix97 commented on orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
> +    }
Validation 이전에 Null 체크를 안하기 때문에 저는 equals 괜찮은거 같습니다

2024-03-13 03:29 UTC, oxix97 commented on orury-client/src/main/java/org/orury/client/review/application/ReviewServiceImpl.java
>          Review review = reviewReader.findById(reviewId)
보통 클래스에 @Transactional(readOnly = true) 설정하고 생성, 수정, 삭제에만 @Transactional 붙이는 것으로 알고 있습니다. @Transactional(readOnly = true)이 부분이 클래스에 들어가는건 대부분 GET이 더 많아서? 라고 저는 생각해여

2024-03-13 03:29 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGender.java
> +    }
return null 하신 이유가 궁금합니다.

2024-03-13 03:29 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGenderConverter.java
> +    }
DB <-> Entity 관련 사항은 InfraException 던지는건 저는 괜찮다고 생각합니다. 어느 계층에서 난 예외인지 명시적으로 알 수 있을거같아여

이미지 로직 작성하면서 외부 통신시 발생하는 오류의 예외 사항도 추가적으로 필요하다 생각하여 하나 더 예외 클래스 추가하는 것에는 저도 동의합니다.

2024-03-13 03:29 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/crew/domain/entity/Crew.java
> +    private boolean isDeleted;
제가 생각한 @Converter는 DB에 그대로 저장이 안되는 Collection, Enum 과 같은 것들을 변환할 목적으로 사용하거나 저희 이미지 로직처럼 부가적으로 파싱해야할 게 있으면 사용한다고 생각합니다.

예를 들어 db에 저장된 is_deleted값이 0~5까지 있을 때 0,1,2,3 -> true, 4,5 -> false 가 되야하는 정책이면 컨버터를 사용하는게 맞지만 단순히 true/ false로 대체될 로직이면 안써도 괜찮다고 생각합니다.

2024-03-13 03:29 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/crew/domain/entity/CrewTag.java
> +    private Crew crew;
해시 태그 같은 역할 이라서 LAZY 로딩 하신건가여?

2024-03-13 03:29 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/global/validation/EnumValidator.java
> +}
해당 코드는 어떤 로직에 사용되는지 궁금합니다

2024-03-13 03:33 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGenderConverter.java
> +    }
지금 InfraImplException이랑 FileException이 있는데,
리팩토링전 코드에서는 이미지를 FileException으로 구분했어서 그대로 이걸로 하면 되지 않을까,,, 싶습니다!

2024-03-13 03:38 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGender.java
> +    }
[JsonCreator](https://green-bin.tistory.com/90)가 없으면 CrewCreateRequest의 gender에 유효하지 않은 값으로 넣으면, 
@Valid까지 도달 안 하고 Json Parsing Error를 뱉어서, 추가해줬습니다!
null 말고 다른 값으로도 설정 가능합니다! "Invalid Gender"과 같이 좀 더 명시적인 값으로 바꿀까요?

2024-03-13 03:40 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/crew/domain/entity/CrewTag.java
> +    private Crew crew;
DB에서 CrewTag를 가져올 때는 이미 Crew를 가져온 상태에서 추가로 CrewTag를 가져오는 상황이 대부분이라,
CrewTag 안에 있는 Crew를 활용할 일은 거의 없을 것이라 생각했기 때문입니다!

2024-03-13 03:46 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/global/validation/EnumValidator.java
> +}
CrewCreateRequest에서 해당 Enum에 포함되는 값인지 확인하는 @EnumValue가 커스텀 어노테이션이라,
어떠한 Enum이라도, 그 Enum에 포함되는지 여부를 확인하는 클래스로 보시면 될듯합니다!
다음 링크 참조했습니다! https://green-bin.tistory.com/90

2024-03-13 05:44 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGender.java
> +    }
gender에 유효하지 않은 값이 들어갈 수 있는 상황이면 예외처리하는게 맞지만 그럴일이 없으면 @JsonCreator가 필요없을거같습니다.

2024-03-13 05:47 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/crew/domain/entity/CrewTag.java
> +    private Crew crew;
CrewTag에 Crew를 쓸일이 없는데 연관관계 때문에 설계하신거면 중간테이블 하나 생성해서 관리하는것도 낫베드일거같습니다 LAZY 로딩 안해도 되서

하지만 CrewTag로 분류할 일이 거의 없으면 이대로 진행하는게 중간 테이블 만드는거보다 괜찮은거 같아여

2024-03-13 05:50 UTC, oxix97 commented on orury-domain/src/main/java/org/orury/domain/global/validation/EnumValidator.java
> +}
확인했습니다~~~

2024-03-13 06:51 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/crew/domain/dto/CrewGender.java
> +    }
프론트에서 크루 생성 시에, "ANY", "FEMALE", "MALE" 이 셋 중 하나로만 보내야 하는데
만약에 다른 값이 온다면 적절한 에러 메세지를 뱉기 위해서 추가하긴 했는데, 이 경우도 배제하고 그냥 지우는게 낫나요??

2024-03-14 01:58 UTC, yejincode approved these changes

2024-03-14 02:34 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewCreateRequest.java
> +        @Min(value = 7, message = "최저 연령을 7세 이상으로 설정해 주세요.")
이거 AOS/IOS 심사 결과가 각각 12세 / 17세로 나와서 12세로 수정해주시는게 좋을 것 같습니다! 공유드리는걸 깜빡했네요

2024-03-14 02:36 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/crew/interfaces/request/CrewCreateRequest.java
> +        @Min(value = 7, message = "최저 연령을 7세 이상으로 설정해 주세요.")
변경 완료했습니다!~

2024-03-14 02:45 UTC, kkkapuq approved these changes
수고하셨습니다!

2024-03-14 03:16 UTC, oxix97 approved these changes

2024-03-14 03:17 UTC, merged