Refactor/#379 image
Kernel360/f1-Orury-Backend pull request #380
Opened 2024-03-13 02:41 UTC by oxix97

## 개요

### AsyncConfig

비동기 관련 로직에 필요한 설정이며, 현재 비동기 예외 처리는 전부 이미지에 대한 예외이기 때문에 코드와 같이 설정했습니다.

### ImageAsyncStore

사실 ImageService역할을 하는 클래스이지만 Facade에서 Service로 사용하자니 변경사항이 너무 많아 AsyncStore로 이름을 지었습니다.
이미지를 비동기로 전송하기 위해서는 미리 임시 파일을 생성하고, 파일들의 이름을 미리 생성해야 하기 때문에 클래스를 별도로 생성하였습니다.
-> 비동기 야무지긴하더라구요

closed #379

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-13 09:07 UTC, GBGreenBravo requested changes

2024-03-13 09:07 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/global/image/ImageAsyncStore.java
따로 빼신 이유가 @Async 메서드를 private으로 설정하지 못해서 그런거겠죠..?
Service와 Store 사이의 레이어라,, 기존 컨벤션 대로 ImageStore 하나만 두는 게 좋을 것 같은데 
아래처럼 AsyncTaskExecutore을 써서 private 메서드도 비동기로 처리할 수 있도록 설정하면, 레이어 분리할 필요 없지 않을까요?
![image](https://github.com/Kernel360/f1-Orury-Backend/assets/147565215/a766a293-884f-4373-a740-df43f0687673)

2024-03-14 02:37 UTC, GBGreenBravo approved these changes

2024-03-14 03:18 UTC, yejincode commented
나도 비동기적으로 일하고 싶다

2024-03-14 03:18 UTC, yejincode approved these changes

2024-03-14 05:05 UTC, kkkapuq approved these changes

2024-03-14 05:05 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/global/image/ImageAsyncStore.java
이친구는 왜 imageStore에 없고 따로 구분지어놓으셨나요? 의도가 궁금합니다.

2024-03-14 05:07 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/global/image/ImageAsyncStore.java
<img width="787" alt="image" src="https://github.com/Kernel360/f1-Orury-Backend/assets/147565215/bb4fa4c0-db09-4e82-a9b7-ab056b5d2bad">
[@Async 사용](https://cano721.tistory.com/208)때문에 다른 클래스로 분리시키셨습니다! 그래서 어제 AsyncTaskExecutor 써서 private 메서드로 활용하려 했는데,, 메서드가 비동기로 작동해도 S3에 저장되지 않는 이슈가 있었습니다...

2024-03-14 05:08 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/global/image/ImageAsyncStore.java
아 이게 민협님이 코멘트 달아둔 내용이었군요; 머쓱

2024-03-14 07:07 UTC, merged