feat : SSE 알림 초기 구현
Kernel360/f1-Orury-Backend pull request #388
Opened 2024-03-14 10:33 UTC by yejincode

## 개요

[참고링크](https://velog.io/@wnguswn7/Project-SseEmitter%EB%A1%9C-%EC%95%8C%EB%A6%BC-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0#%EF%B8%8F-%EC%95%8C%EB%A6%BC-service)

SSE 알림 중, 위의 링크에서 구현된 내용이 저희 프로젝트와 구조가 비슷해서 위의 코드를 토대로 작성했습니다.
참고한 내용 중에 제가 생각했을 때 보완이 필요한 부분들을 TODO 주석으로 달아뒀는데, 제가 아직 SSE에 대한 이해가 부족해서 정확하지 않을 수 있습니다.

현재 서버 메모리에 저장된 객체를 확인하기 위해 임시로 controller에서 SseRepository를 사용하고 있는데, 좋은 방법이 아닌 것 같습니다. 좋은 아이디어가 있다면 공유 부탁드립니다!

* SseRepository에 있는 Emitter, EventCache 객체는 서버 메모리에 저장됩니다. 
* Notification 객체는 DB에 저장됩니다. 링크에는 구현이 안되어있지만, 추후에 해당 Notification으로 알림함 기능까지 구현하면 될 것 같습니다.
* subscribe까진 잘 되는 것으로 테스트했는데, send에서 event가 저장되지 않는 이슈가 있는 듯합니다. 기존의 방식으로 테스트하는데에는 한계가 있어서, 더 공부하면서 테스트 해봐야할 것 같습니다. 

closed #373

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-18 03:44 UTC, GBGreenBravo requested changes

2024-03-18 03:44 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/notification/application/NotificationServiceImpl.java
> +        String eventId = userDto.id().toString() + "_" + System.currentTimeMillis();
이것도 makeTimeIncludeId() 활용하면 좋을 것 같습니다~!

2024-03-18 03:44 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/notification/infrastructure/EmitterRepositoryImpl.java
> +                    if (key.startsWith(userId.toString())) {
코드를 참조하신 링크에서는 userName이라는 이메일로 구분을 해서 상관이 없겠지만,
이 코드에서 userId를 쓴다면 다음과 같은 상황에서 예상되는 이슈가 있습니다.
userId 11을 가진 유저가 이 메서드를 호출한다면, 11*, 11**, 11*** 등 다른 유저의 Emitter도 삭제될 것으로 예상됩니다.

그래서 emitterId를 생성할 때 썼던 _ 구분자를 추가해주면 해결이 될 것으로 생각됩니다!
startsWith()를 사용하는 이 클래스의 다른 메서드들에도 적용이 필요해 보입니다!

2024-03-18 03:44 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/notification/application/NotificationServiceImpl.java
> +        return !lastEventId.isEmpty();
Strings.isNotEmpty() 쓰면 가독성이 조금 더 좋아질까요..?

2024-03-18 03:44 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/notification/application/NotificationServiceImpl.java
> +        }
이건 CustomException이 아닌 IOException 그대로 둬야 하는 거 아닐까요?
클라이언트에서 연결의 끊었을때, 이를 파악하기 위한 Exception으로 보입니다!

따라서 Custom Exception을 설정하려면 별도의 catch문을 둬야할 것으로 생각합니다!

2024-03-18 03:44 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/notification/interfaces/response/NotificationResponse.java
반환정보는 response에 담는다는 컨벤션에 맞춰 이를 생성하신 걸로 유추됩니다!
그런데, 현재로서는 NotificationDto가 변형되어 반환되는 곳이, 알림반환밖에 없는 걸로 파악되어,
추후에도 NotificationDto에 따른 response가 따로 생기는 것이 아니라면 Response 말고 NotificationDto 그대로 반환돼도 괜찮을 것 같습니다!

2024-03-18 04:37 UTC, yejincode commented on orury-domain/src/main/java/org/orury/domain/notification/infrastructure/EmitterRepositoryImpl.java
> +                    if (key.startsWith(userId.toString())) {
오 생각도 못했습니다 이 부분 반영하겠습니다 !

2024-03-18 05:06 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/notification/application/NotificationServiceImpl.java
> +        }
알람에 대한 익셉션을 따로 뺴야겠다고 생각했어서 TODO로 달아뒀는데, 해당 부분은 IOException 그대로 가는 것이 맞겠네요 ! 해당 주석은 지우도록 하겠습니다.

2024-03-18 05:14 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/notification/interfaces/response/NotificationResponse.java
넵 다른 도메인들은 다 response에 담아 반환하기에 컨벤션에 맞추는 것이 좋다고 생각하여 생성했습니다. 
현재로서는 Dto 그대로 반환해도 괜찮지만, 알림에 대한 기획이 명확히 나오지 않았기에 저도 추후에 기획에 따라 Dto 그대로 반환해도 괜찮을 것 같습니다 !

2024-03-18 05:15 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/notification/application/NotificationServiceImpl.java
> +        return !lastEventId.isEmpty();
더 좋은 것 같습니다 ! 반영하겠습니다

2024-03-19 08:06 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/notification/interfaces/NotificationController.java
> +        return notificationService.subscribe(userPrincipal.id(), lastEventId);
해당 로직은 컨트롤러에서 퍼사드를 거치지 않고 바로 서비스를 호출하는 이유가 있을까요?

2024-03-19 08:06 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/notification/application/NotificationServiceImpl.java
> +        sendNotification(emitter, eventId, emitterId, "EventStream Created. [userId=" + userId + "]");
이부분이 조금 이해가 안가는데 설명 한 번 해주실 수 있으실까요?
503 에러가 왜 뜨는거고, 더미 이벤트는 왜 전송하는지 궁금합니다

2024-03-19 08:31 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/notification/interfaces/NotificationController.java
> +        return notificationService.subscribe(userPrincipal.id(), lastEventId);
지금은 알림함 조회 API, 읽음 여부 API 등이 추가되면서 NotificationFacade를 생성했지만, 초기에 구현할 때에는 controller에서 subscribe API만 있어서 하나의 메서드 때문에 Facade를 생성할 필요가 없을 것 같아서 바로 서비스를 호출했습니다. 
지금은 Facade가 생겼으니 Facade를 통해 호출하는 것으로 수정하겠습니다 !

2024-03-19 08:33 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/notification/application/NotificationServiceImpl.java
> +        sendNotification(emitter, eventId, emitterId, "EventStream Created. [userId=" + userId + "]");
제가 알기로는,
emitter는 타임아웃이 나면 클라이언트에서 자동으로 재연결을 시도하는데 , 한 번도 이벤트를 수신한 내역이 없으면 503 에러가 뜬다고 합니다.
해서, 503 에러를 방지하기 위해 emitter 객체를 생성했을 때, 더미이벤트를 전송합니다.

2024-03-19 08:42 UTC, kkkapuq approved these changes
수고하셨습니다!

2024-03-20 02:48 UTC, GBGreenBravo approved these changes

2024-03-20 03:10 UTC, oxix97 requested changes
수고하셨습니다~~~

2024-03-20 03:10 UTC, oxix97 commented on orury-client/src/main/java/org/orury/client/notification/interfaces/NotificationController.java
> +    @GetMapping(value = "/getemitter")
url에 get,post 같은 내용을 첨부하는 것 보다 /getemitter -> /emitter 로 변경하는것도 괜찮을 것 같습니다!!

2024-03-20 03:10 UTC, oxix97 commented on orury-client/src/main/java/org/orury/client/notification/interfaces/response/NotificationResponse.java
> +        String url
알림 타입을 결정하는게 url 인건가여?

2024-03-20 03:11 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/notification/interfaces/NotificationController.java
> +    @GetMapping(value = "/getemitter")
넵 이 메서드는 지금 임시로 추가한 api라서 추후에 삭제하도록 하겠습니다!

2024-03-20 03:13 UTC, yejincode commented on orury-client/src/main/java/org/orury/client/notification/interfaces/response/NotificationResponse.java
> +        String url
url은 바로 연결될 수 있는 링크로 생각했습니다. 
알림 타입 같은 경우에는 도메인별(크루, 게시글, ...) 등으로 나누진 않습니다.
대신에 현재 나온 UI를 보면, 알림 제목(크루 이름, 유저 이름)이 필요해서 title에 담을 수 있게 했습니다.

2024-03-20 03:20 UTC, oxix97 commented on orury-client/src/main/java/org/orury/client/notification/interfaces/response/NotificationResponse.java
> +        String url
당장 사용하기에는 타입으로 나누는 것보다 링크가 좀 더 직관적인거 같습니다.

2024-03-20 03:20 UTC, oxix97 approved these changes

2024-03-20 03:20 UTC, merged