Refacto : image 패키지 생성 & 크루 default-image 반영
Kernel360/f1-Orury-Backend pull request #407
Opened 2024-03-26 09:51 UTC by GBGreenBravo

## 개요

closed #406

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-27 07:01 UTC, yejincode approved these changes
반영 내용 확인했습니다 감사합니다 :)

2024-03-28 08:51 UTC, GBGreenBravo commented
내 가입/신청 크루 목록 조회 API를 구현할 때,
JoinedTime이나 AppliedTime을 어떤 레이어에서 결합하느냐에 따라 2가지 옵션이 있을 듯 합니다!

1. Facade에서 결합
  - CrewsResponse를 구성할 때 인자로 JoinedTime/AppliedTime을 담기에, CrewDto에는 영향 없음.
  - 그러나 CrewFacade에서 CrewService 메서드를 여러번 호출해야 한다는 단점. (CrewDtos가져오고, 각 crewDto에 따른 가입/신청time조회)
2. Service에서 결합
  - CrewDto 구성할 때, JoinedTime/AppliedTime을 담아야 하므로, CrewDto에 2개의 새 필드가 추가됨. (Aggregate 개념에 의해 비합리적이지는 않아보임.)
  - CrewDto에 다른 기능에서는 활용하지 않는 필드 늘어난다는 단점. (DDD강의의 Info 개념이 적용될 여지 있어보임)

2024-04-08 05:32 UTC, oxix97 requested changes
수고하셨습니다~~~

2024-04-08 05:32 UTC, oxix97 commented on orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
>      }
어떤 로직인지 설명 가능할까여??

2024-04-08 05:32 UTC, oxix97 commented on orury-client/src/main/java/org/orury/client/meeting/application/MeetingServiceImpl.java
> +        userImages.add(0, meetingCreator.profileImage());
이것도 동일합니다22

2024-04-09 01:56 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
>      }
크루에 해당하는 유저들 이미지를 maximumCount만큼 가져오는 메서드인데, 매번 크루장의 이미지가 맨 처음에 있어야 하는 요구사항이 있었습니다!

변경 전: List<String>을 새로 선언 -> 크루장 이미지 추가 -> 다른 크루원 이미지 삽입
굳이 변경 안 해도 되는 건데, 크루장 이미지 추가 부분이 눈에 잘 띄지 않아 아래의 방식이 가독성이 더 낫지 않을까 해서 변경해봤습니다! 혹시 더 이상하다고 느껴진다면 롤백하겠습니다!
변경 후: 다른 크루원 이미지 가변리스트로 반환 -> 맨 앞에 크루장 이미지 추가

2024-04-09 01:58 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/meeting/application/MeetingServiceImpl.java
> +        userImages.add(0, meetingCreator.profileImage());
위 답변과 동일한 변경사항 적용됐습니다! 마찬가지로 이상하면 롤백하겠습니다~

2024-04-09 06:40 UTC, kkkapuq approved these changes

2024-04-09 06:40 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
> +    boolean existCrewMember(Long crewId, Long userId);
PK를 사용하지 않는 이유가 뭘까요?

2024-04-09 06:40 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/crew/application/CrewServiceImpl.java
>      }
저도 스트림으로 표현하는게 좀 더 깔끔해보입니다!

2024-04-09 06:45 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/crew/application/CrewService.java
> +    boolean existCrewMember(Long crewId, Long userId);
CrewMemberPK crewMemberPK = CrewMemberPK.of(userId, crewId);
기존 대로라면 Facade에서 위와 같이, CrewMemberPK를 생성해줘야 하는 작업이 무조건 요구되는데, 
해당 로직이 application레이어에 있을만한 중요한 로직이 아니라, 
CrewMemberReader의 메서드와 결합돼 있는 것이 적절하다고 생각되어 해당 인자를 크루id와 유저id로 받도록 했습니다!

2024-04-09 06:57 UTC, oxix97 approved these changes

2024-04-09 06:58 UTC, merged