Issue#27
Kernel360/f1-Orury-Backend pull request #41
Opened 2023-12-15 09:41 UTC by yejincode

## 개요

closed #

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2023-12-15 09:51 UTC, GBGreenBravo commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/controller/UserController.java
> +                .message("OK")
이 부분은 하드코딩하지 않고,
Contants에 상수 처리 하거나, HttpStatus.OK.value().toString()으로 처리하시면 좋을 듯 합니다!

2023-12-15 09:54 UTC, oxix97 approved these changes
수고하셨습니다,

2023-12-15 09:55 UTC, oxix97 commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/request/RequestUserInfo.java
> +                requestUserInfo.nickname(),
DTO 레벨에 Request를 넣은 이유가 궁금합니다~~

2023-12-18 05:16 UTC, kkkapuq requested changes
수고하셨습니다.

개인적으로는 모두 API를 작성할 때
@Operation(summary = "API 명", description = "API 세부 설명")
이 어노테이션을 붙이는게 좋을 것 같습니다.
swagger 작업이 나중에 필요하긴한데, 한 번에 할 때 좋을 것 같아서요

2023-12-18 05:16 UTC, kkkapuq commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/model/User.java
> +    private User(String email, String nickname, String Password, int signUpType, int gender, LocalDate birthday, String profileImage) {
`Password` -> `password` 로 수정하는게 좋을 것 같습니다

2023-12-18 05:16 UTC, kkkapuq commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/model/User.java
> +    }
이부분 민협님이 어노테이션으로 공유주신 내용 참고해서 수정하는게 컨벤션이 맞을 것 같습니다!

2023-12-18 05:58 UTC, kkkapuq commented on orury-api/src/main/java/org/fastcampus/oruryapi/global/error/code/UserErrorCode.java
> +    NOT_FOUND_USER(HttpStatus.NOT_FOUND.value(),"유저를 찾을 수 없습니다.");
"유저를 찾을 수 없습니다." 를 ErrorMessage.java의 USER_NOT_FOUND 로 선언하고 사용하는게 컨벤션에 맞을 것 같습니다!

2023-12-18 06:02 UTC, yejincode commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/controller/UserController.java
> +                .message("OK")
넵 해당 부분 UserMessage 로 추가하여서 하드코딩 되지 않도록 수정했습니다 !

2023-12-18 06:03 UTC, yejincode commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/converter/request/RequestUserInfo.java
> +                requestUserInfo.nickname(),
저는 컨트롤러보다 서비스단에서 request->dto로 변환하는 것으로 생각하여, 해당 부분 민협님과 맞춰서 진행했습니다 !

2023-12-18 06:13 UTC, yejincode commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/controller/UserController.java
> +                .message("OK")
해당 어노테이션은 처음 알았네요,, ! 어노테이션 붙여서 다시 커밋 날렸습니다. 
추가로 하드코딩된 부분은 User 도메인 내에 util/UserMessage 를 새로 만들어서 처리했습니다 감사합니다 !

2023-12-18 06:14 UTC, yejincode commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/model/User.java
> +    private User(String email, String nickname, String Password, int signUpType, int gender, LocalDate birthday, String profileImage) {
병합 과정에서 꼬였나보네요,, 해당 부분도 다시 커밋 날렸습니다. !

2023-12-18 06:16 UTC, yejincode commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/model/User.java
> +    }
이 부분도 역시,,, 병합 과정에서 꼬인 것 같습니다 감사합니다 !

2023-12-18 06:21 UTC, yejincode commented on orury-api/src/main/java/org/fastcampus/oruryapi/global/error/code/UserErrorCode.java
> +    NOT_FOUND_USER(HttpStatus.NOT_FOUND.value(),"유저를 찾을 수 없습니다.");
감사합니다 커밋 날렸습니다!!

2023-12-18 06:29 UTC, kkkapuq approved these changes
반영 감사합니다 수고하셨습니다 :)

2023-12-18 06:30 UTC, GBGreenBravo commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/service/UserService.java
>  @Transactional
@Transactional를 메서드별로 달기로 했던 것 같아, 이 부분 반영해주시면 감사하겠습니다~!

2023-12-18 06:31 UTC, GBGreenBravo commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/repository/UserRepository.java
> +@Repository
@Repository 이 어노테이션 없어도 동작하는 걸로 아는데, 따로 어노테이션을 다신 이유가 궁금합니다!

2023-12-18 06:34 UTC, yejincode commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/service/UserService.java
>  @Transactional
넵 !!

2023-12-18 06:35 UTC, yejincode commented on orury-api/src/main/java/org/fastcampus/oruryapi/domain/user/db/repository/UserRepository.java
> +@Repository
JPA 레포지토리를 상속받으면 어노테이션 없이도 동작을 하는군요..! 하나 배워갑니다 !

2023-12-18 07:33 UTC, merged