Feat : (가입한/가입신청한) 내 크루 목록 조회 API 구현
Kernel360/f1-Orury-Backend pull request #421
Opened 2024-04-09 07:44 UTC by GBGreenBravo

## 개요
내 가입/신청 크루 목록 조회 API를 구현할 때,
JoinedTime이나 AppliedTime을 어떤 레이어에서 결합하느냐에 따라 아래의 2가지 옵션이 있을 듯합니다.

1. Facade에서 결합
    - CrewsResponse를 구성할 때 인자로 JoinedTime/AppliedTime을 담기에, CrewDto에는 영향 없음.
    - 그러나 CrewFacade에서 CrewService 메서드를 여러번 호출해야 한다는 단점.
    (CrewDtos가져오고, 각 crewDto에 따른 가입/신청time조회)

2. Service에서 결합
    - CrewDto 구성할 때, JoinedTime/AppliedTime을 담아야 하므로, CrewDto에 2개의 새 필드가 추가됨.
    (Aggregate 개념에 의해 비합리적이지는 않아보임.)
    - CrewDto에 다른 기능에서는 활용하지 않는 필드 늘어난다는 단점.
    (DDD강의의 Info 개념이 적용될 여지 있어보임)

위 선택지에서 1번을 선택하여 구현했습니다. 그래서 CrewService에 많은 메서드가 생겨, 이를 원치 않는다면 CrewDto에 변경을 감수해서 2번을 채택하는 것이 좋을 듯 합니다. 혹시나 다른 방식이 있다면 언제든 환영입니다!!

추가로, CrewFacade에 코드 중복을 줄이기 위해, 인자와 반환 타입을 지정한 인터페이스(BiFunction과 TriFunction)를 활용해서
convertCrewDtosToCrewsResponses()를 구현했는데 이 방식이 더 가독성이 떨어진다면 해당 메서드 삭제하겠습니다!

closed #420

## PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-04-16 02:52 UTC, kkkapuq requested changes
수고하셨습니다 BiFunction과 TriFunction을 이렇게 사용하셨군요.. 갓

2024-04-16 02:52 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
> +        return convertCrewDtosToCrewsResponses(crewDtos, userId, crewService::getJoinedAt, CrewsResponse::ofWithJoinedTime);
전 BiFunction 쓰는게 훨씬 깔끔해보여서 좋습니다

2024-04-16 02:52 UTC, kkkapuq commented on orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
> +    @Operation(summary = "내 크루 조회", description = "내가 가입한 크루를 조회한다.")
@Operation(summary = "가입 신청한 크루 조회", description = "내가 가입 신청한 크루를 조회한다.")
로 수정하는게 좋을 것 같습니다!

2024-04-16 03:23 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/crew/interfaces/CrewController.java
> +    @Operation(summary = "내 크루 조회", description = "내가 가입한 크루를 조회한다.")
반영 완료했습니다!

2024-04-22 00:02 UTC, kkkapuq approved these changes
수고하셨습니다~!

2024-04-22 01:12 UTC, oxix97 approved these changes
수고하셨습니다~~

2024-04-22 01:12 UTC, oxix97 commented on orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
> +                    return triFunction.apply(crewDto, userImages, time);
apply는 어디서 구현이 된건가여?

2024-04-22 01:28 UTC, yejincode approved these changes

2024-04-22 01:43 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/crew/application/CrewFacade.java
> +                    return triFunction.apply(crewDto, userImages, time);
apply는 biFinction이랑 triFunction에서 제공하는 거라, 해당 메서드를 적용한다는 뜻입니다~!

2024-04-22 02:18 UTC, merged