Fix : 운영시간이 null인 경우 오류 수정 및 요일 정렬 처리
Kernel360/f1-Orury-Backend pull request #436
Opened 2024-04-22 06:26 UTC by kkkapuq

## 개요
암장 조회 시 운영시간이 null이면 해당 암장 조회가 불가능한 이슈가 있었습니다. 이를 해결 + 월화수목금토일 순으로 노출처리 진행했습니다.

### 상세 내용
- Map.entry는 null을 허용하지 않아서, 이를 SimpleEntry라는 친구로 바꿨습니다. 얘는 null을 허용해주는 Entry 클래스라고 하네요.
- 정렬의 경우 월화수목금토일 별로 int값을 가지는 map을 선언해주고, 이 친구와 comparingInt 하는 방식으로 정렬처리했습니다.. 더 좋은 방법이 있다면 지적 부탁드립니다.

closed #435 

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [x] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-04-23 03:24 UTC, GBGreenBravo requested changes
형준님께서 변경하신 것처럼, 
기존에 Map.Entry를 담고 있던 Set 때문에 정렬이 안되었던 것 같습니다.
GymDto의 EnumMap의 Key인 DayOfWeek는 월화수목금토일 순으로 정렬돼 있어, dayOrder 선언은 안 하셔도 될 듯합니다!

그래서 null 허용을 해결해주기 위해서 GymResponse의 필드를 아래와 같이 선언하고,
`List<AbstractMap.SimpleEntry<String, String>> businessHours,`

of() 메서드에 구현된 koreanBusinessHours 코드를 아래 코드로 교체하는 방식이 더 간편하지 싶습니다!
`List<AbstractMap.SimpleEntry<String, String>> koreanBusinessHours = gymDto.businessHours().entrySet().stream()
                .map(entry -> new AbstractMap.SimpleEntry<>(entry.getKey().getDisplayName(TextStyle.NARROW, Locale.KOREAN), entry.getValue()))
                .toList();`

2024-04-23 03:34 UTC, oxix97 commented
따로 선언안해도 되면 저도 민협님 의견에 동의합니다

2024-04-23 03:34 UTC, oxix97 approved these changes
수고하셨습니다~~

2024-04-23 17:34 UTC, yejincode approved these changes
stream 천재시네요 부럽습니다,, 
order부분 관해서는 민협님 리뷰대로 진행해도 좋을 것 같습니다 
수고하셨습니다 !

2024-04-24 02:19 UTC, kkkapuq commented
> 형준님께서 변경하신 것처럼, 기존에 Map.Entry를 담고 있던 Set 때문에 정렬이 안되었던 것 같습니다. GymDto의 EnumMap의 Key인 DayOfWeek는 월화수목금토일 순으로 정렬돼 있어, dayOrder 선언은 안 하셔도 될 듯합니다!
> 
> 그래서 null 허용을 해결해주기 위해서 GymResponse의 필드를 아래와 같이 선언하고, `List<AbstractMap.SimpleEntry<String, String>> businessHours,`
> 
> of() 메서드에 구현된 koreanBusinessHours 코드를 아래 코드로 교체하는 방식이 더 간편하지 싶습니다! `List<AbstractMap.SimpleEntry<String, String>> koreanBusinessHours = gymDto.businessHours().entrySet().stream() .map(entry -> new AbstractMap.SimpleEntry<>(entry.getKey().getDisplayName(TextStyle.NARROW, Locale.KOREAN), entry.getValue())) .toList();`

쓰읍... 이생각을 못했네요 애초에 반환값을 SimpleEntry로 하면 됐었군요.
피드백 감사합니다! 반영완료했어요

2024-04-24 02:30 UTC, GBGreenBravo approved these changes
Null 허용하는 SimpleEntry 잘 배웠습니다!~!

2024-04-24 03:12 UTC, merged