Feat : 신고기능 개발
Kernel360/f1-Orury-Backend pull request #453
Opened 2024-04-30 08:46 UTC by kkkapuq

## 개요
게시글, 댓글에 대한 신고기능을 추가했습니다.
Report를 어떤 도메인에 넣어야 하나 좀 고민을 했는데, 게시글이나 댓글에 대한 신고여도 결국은 유저를 제제하기 위함이니, 유저 도메인에서 개발을 진행했습니다.

게시글, 댓글에 대한 타입을 request로 받아서 report 테이블에 저장하는 로직입니다.

### 상세 내용
**report 테이블**
<img width="310" alt="image" src="https://github.com/Kernel360/f1-Orury-Backend/assets/44130863/a87c5f28-308d-4276-b379-6f9bc3328973">
reason은 ReportInfo의 코드,
type은 ReportType의 코드값과 매핑됩니다.

**타입에 따른 분기처리**
<img width="735" alt="image" src="https://github.com/Kernel360/f1-Orury-Backend/assets/44130863/404ba57a-3f1d-4341-a7eb-1f0eaf69e5c9">
이부분을 좀 깔끔하게 코드를 작성하고싶었는데.. 함수로 따로 빼도 if문의 연속이라 그냥 serviceImpl에 로직을 박았습니다.
로그인의 전략패턴처럼 한다면 할 수는 있는데.. 뭔가 이거 하나를 위해서 전략패턴을 적용하는건 또 그거 나름대로 오버엔지니어링인것같고..
좋은 코드로 개선할 수 있도록 피드백 주시면 감사하겠습니다.

closed #449 

## PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 배포 및 PR 관련

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. [Commit message convention 참고](https://www.notion.so/e3110b52de8442e18f60b23a85933dbb?pvs=4).
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-04-30 11:31 UTC, GBGreenBravo commented
![image](https://github.com/Kernel360/f1-Orury-Backend/assets/147565215/8ed10ef4-76ea-4673-8e03-308f2d8e9429)
위 코드에서 post랑 comment는 따로 안 쓰이고 유효한지만 검사하는 거죠?

2024-04-30 11:47 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/user/domain/entity/Report.java
> +    private int type;
이 필드를 Enum으로 관리하는 건 어떨까요?
<img width="818" alt="image" src="https://github.com/Kernel360/f1-Orury-Backend/assets/147565215/f7d093e6-382f-4a10-96dc-346e4b3fbed3">
위와 같이 Enum과 추상메서드로 구현해준다면, UserServiceImpl의 report메서드에서는 아래와 같이 조금 더 간단하게 구현이 가능할 듯 합니다!
물론 이 방식도 report 대상이 늘어남에 따라 인자가 계속 늘어난다는 찝찝함이 남긴 하네요..!
<img width="666" alt="image" src="https://github.com/Kernel360/f1-Orury-Backend/assets/147565215/dd16e4d7-c0bd-4a9a-8ee8-b2c5726d578b">

2024-04-30 12:24 UTC, GBGreenBravo requested changes

2024-04-30 12:24 UTC, GBGreenBravo commented on orury-client/src/main/java/org/orury/client/user/application/UserServiceImpl.java
> +    public void reportUser(ReportDto reportDto) {
이미 신고한 댓글이나 게시글에 대해서는 "이미 신고한 게시글/댓글 입니다" 예외처리가 있었으면 합니다!

2024-04-30 12:24 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/user/domain/entity/Report.java
> +    private User reportUser;
ReportDto와 마찬가지로 reporter, reportee 변수명을 쓰는 건 어떨까요?
DB의 reporter_id와 ReportDto의 reportee가 같은 걸로 이해해서, DB 필드명도 바꾸는 게 어떨까 제안드립니다!

2024-05-01 02:15 UTC, kkkapuq commented
> ![image](https://private-user-images.githubusercontent.com/147565215/326786791-8ed10ef4-76ea-4673-8e03-308f2d8e9429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1Mjk5NzgsIm5iZiI6MTcxNDUyOTY3OCwicGF0aCI6Ii8xNDc1NjUyMTUvMzI2Nzg2NzkxLThlZDEwZWY0LTc2ZWEtNDY3My04ZTAzLTMwOGYyZDhlOTQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQwMjE0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTdlOTRiN2ExYzY5MmIzZDgwOGMyZjM5MTBlMmI5MTk3NmM3YzhlYzY3MGIyOTg0MDZhY2U2NzI0MWYxZWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6kTZf0g37Et_zLMUqtVY23erI0QXDVWxIs_eKkFKY78) 위 코드에서 post랑 comment는 따로 안 쓰이고 유효한지만 검사하는 거죠?

네 맞습니당

2024-05-01 02:16 UTC, kkkapuq commented on orury-domain/src/main/java/org/orury/domain/user/domain/entity/Report.java
> +    private int type;
아니 이런식으로...사용이 가능한거였군요..? 그는 자바의 신인가?
해봤자 enum이 길어지는데 한계가 있는 영역이라 이게 좋을 것 같습니다

2024-05-01 02:18 UTC, GBGreenBravo commented on orury-domain/src/main/java/org/orury/domain/user/domain/entity/Report.java
> +    private int type;
https://github.com/Kernel360/F1-WashFit-BE/blob/develop/module-api/src/main/java/com/kernel360/main/enumset/Sort.java
위 링크의 워시핏에서 개발한 게 기억이 나서 적용해봤슴다 ㅎㅎ

2024-05-01 15:53 UTC, kkkapuq commented on orury-domain/src/main/java/org/orury/domain/user/domain/entity/Report.java
> +    private int type;
와 다른팀 플젝 코드도 보시는군요...GOAT...

2024-05-02 04:37 UTC, kkkapuq commented on orury-domain/src/main/java/org/orury/domain/user/domain/entity/Report.java
> +    private int type;
반영완료!

2024-05-02 06:01 UTC, GBGreenBravo approved these changes

2024-05-07 01:18 UTC, c0olcode approved these changes
수고하셨습니다 !

2024-05-08 05:07 UTC, merged